cmake_minimum_required(VERSION 3.16)
project(Filogenia LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(filogenia src/main.cpp)
add_executable(pruebas tests/tests.cpp)
if(MSVC)
    target_compile_options(filogenia PRIVATE /utf-8)
    target_compile_options(pruebas PRIVATE /utf-8)
endif()
enable_testing()
add_test(NAME algoritmos COMMAND pruebas)
